import Head from 'next/head'
import styles from 'styles/Home.module.scss'
import Header from 'components/header'
import Featured from 'components/featured'
import Products from 'components/products'
import createFirebaseApp from 'firebase/firebase'
import {
  collection,
  DocumentData,
  getDocs,
  getFirestore,
} from 'firebase/firestore'
type Props = {
  productsArray: DocumentData[]
}
const Home = ({ productsArray }: Props) => {
  const productsList = productsArray.filter(
    (products) => products.featured === false
  )
  const featuredProducts = productsArray.filter(
    (products) => products.featured === true
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Featured featuredProducts={featuredProducts} />
        <hr />
        <Products productsArray={productsList} />
      </main>
    </div>
  )
}

export default Home

export async function getServerSideProps() {
  // Fetch products data from firebase API
  const app = createFirebaseApp()
  const db = getFirestore(app)
  const productsRef = collection(db, 'products')
  const productsArray: DocumentData[] = []
  const querySnapshot = await getDocs(productsRef)
  querySnapshot.forEach((doc) => {
    productsArray.push(doc.data())
  })
  return { props: { productsArray } }
}
